### ISSUE TITLE
Search by DOI returns multiple records in different states

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#76]
## 🐛 Describe the bug

Not sure if this a bug on the DOI UI or the DOI Service, but a query for a specific DOI returns 2 records in 2 different states:

## 📜 To Reproduce
1. Start up DOI UI
2. Go to http://localhost:3000/#/search/10.17189/1522357
3. Get the following search results:
<img width="1305" alt="Screen Shot 2021-07-17 at 11 54 43 AM" src="https://user-images.githubusercontent.com/33492486/126047149-761df2f0-4534-4a6d-a91b-435770fef42b.png">

## 🕵️ Expected behavior

Should only return one record with the current state of the DOI.

---

** :unicorn: Applicable requirements
🦄 #36

**Comment by collinss-jpl** [comment]
@jordanpadams @tloubrieu-jpl I've taken some time to try to reproduce this using the latest version of the service and API (but without UI), and I cannot reproduce it. I attempted to reproduce by:

* Importing **production** DOI's from OSTI to local database
* Moving the DOI used in the example (10.17189/1522357) back to draft so it has multiple entries in the Sqlite3 table
* Querying for 10.17189/1522357 via list action directly, and through the API

In both cases, only the latest row for the DOI was returned. My guess is this issue was related to a bug in the database code for fetching the "is_latest" row that was fixed as part of an unrelated PR. However, its hard to say exactly because we've lost a lot of the commit history for the pds-doi-repo. My recommendation would be to redeploy latest ver of DOI service, and see if you can still reproduce this bug. I'm fine with leaving this ticket open until then.

**Comment by collinss-jpl** [comment]
@jordanpadams @tloubrieu-jpl  I went ahead and tried to reproduce this issue with the DOI service currently deployed on pds-dev3 and was still unable to. I pretty much followed the steps I outlined above: 

* Imported production OSTI records to local database (existing db seemed to be empty still)
* Moved DOI 10.17189/1522357 back to draft, and then even moved it forward to the "review" state for good measure
* Queried 10.17189/1522357 via list action and through API. In both cases only most up-to-date row was returned.

I also tried to launch the UI to see if was still occurring there, but I was unable to navigate to the search page using http://localhost:3000/#/search/10.17189/1522357, just kept redirecting me to the "Reserve or Release" page.

@eddiesarevalo I also noticed that the UI still needs to be updated to point at v0.2 of the API. Besides just replacing "0.1" with "0.2" in the URL's, there have also been some updates to semantics of the endpoints themselves. I left an instance of the API running on pds-dev3 on port 8080. If you tunnel to that port on your local machine (`ssh -L 8080:localhost:8080 pds-dev3`) you can try out the new version by navigating to http://localhost:8080/PDS_APIs/pds_doi_api/0.2/ui/

**Comment by tloubrieu-jpl** [comment]
That did not show again. Not much time to check more.
